### ISSUE TITLE
Demo Milestone

### ISSUE THREAD

**Issue by JadenBalogh** [ubco-video-game-development-club/rpg#143]
PRIORITIZED
 - [x] Main menu
 - [x] Wind VFX
 - [x] Post processing FX
 - [x] HUD
 - [x] UI Font
 - [x] Town level design
 - [x] Backyard level design
 - [x] Level connections (doors between levels)
 - [x] Death / respawning
 - [x] Dialogue / story full implementation
 - [x] Quest completion
 - [x] Demo end menu
 - [x] Leaf VFX

See #145 for Art checklist!
