### ISSUE TITLE
Demo Milestone Art

### ISSUE THREAD

**Issue by JadenBalogh** [ubco-video-game-development-club/rpg#145]
PRIORITIZED:
 - [x] Find a font for UI
 - [x] Change existing static sprites to match line art style (trees and such)
 - [x] Update player idle/move
 - [x] Add little leaf image for particle effect
 - [x] Change jimmy idle/move to match current style
 - [x] Wooden fence: top-left and top-right pieces only
 - [x] Flowers and rocks to be placed on top of grass
 - [x] General bee idle/move animation - can be reused for all bees and use the same animation (bobbing) for idle AND move
 - [x] Player attack animation
 - [x] Slight visual variations for the bee types idle animations (colors, clothes?)
 - [x] Queen bee idle animation
 - [x] General bee "action" animation - reuse for all attacks (they quickly buzz forward aggressively maybe?) with visual variations for each bee
 - [x] Add head profiles for dialogue
 - [x] Extra NPCs around the town (idle)
 - [x] Main menu background art
 - [x] Add Jimmy attack anim

These should be ROUGH. Especially the animations. Like, a few frames, does not need to look proper. We just need to visually see the action.

See #143 for summary.
